Models/ErrorViewModel.cs
using System;

namespace SalaEscape.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Escape.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SalaEscape.Models
{
    static public class Escape
    {
        static List <string> IncognitasSalas=  new List <string>{} ;
        //lo pusimos en el controller
        private static int _estadoJuego=1;
       
       public static int EstadoJuego
        {
            get
            {
                return _estadoJuego;
            }
        }

        public static void IniciarJuego()
        {
            _estadoJuego = 1;
        }

        static void InicializarLista()
        {
            IncognitasSalas.Add("");
            string incognita1 = "1997-06-26";
            IncognitasSalas.Add(incognita1);
            string incognita2 = "6";
            IncognitasSalas.Add(incognita2);
            string incognita3 = "Gryffindor";
            IncognitasSalas.Add(incognita3);
            string incognita4 = "humano";
            IncognitasSalas.Add(incognita4);
        }

        public static bool ResolverSala(int Sala, string Incognita)
        {
            InicializarLista();
            if (IncognitasSalas[Sala] == Incognita)
            {
                _estadoJuego = Sala+1;
                return true;
            }
            else
            {
                _estadoJuego = Sala;
                return false;              
            }

        }
         
    }
}

Controllers/EscapeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using SalaEscape.Models;

namespace SalaEscape.Controllers
{
     public class EscapeController : Controller
    {

    
        public IActionResult Comenzar()
        {
            Escape.IniciarJuego();
            return View("Habitacion1");
            
        }
         public IActionResult Index()
        {
            return View();
        }
        [HttpPost] public IActionResult Habitacion(int sala, string clave)
        {
            bool respuesta;
            respuesta = Escape.ResolverSala(sala, clave);

            string vista;

            if(respuesta == false)
            {
                ViewBag.Error="Ha ingresado una respuesta erronea, vuelva a intentarlo";
            }
          

            if (Escape.EstadoJuego == 5)
            {
                vista = "Victoria";
            }
            else
            {
                vista = "Habitacion" + (Escape.EstadoJuego);
            }
            
            return View(vista);
            
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SalaEscape.Models;

namespace SalaEscape.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }


        public IActionResult Tutorial()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Views/Escape/Habitacion1.cshtml
<div class="text-center">
  <h1>Sala 1</h1>
<P> 
Harry se encuentra encadenado a una silla en el sótano debajo de las escaleras, claramente no puede liberarse solo. Ayúdalo a encontrar la llave de sus esposas descubriendo el siguiente acertijo… 
</p>

<img src="\imagenes\sala 1 oka.jpg">
 <P> @ViewBag.Error </p>
<form method="post" action='@Url.Action("Habitacion","Escape")'>
  <p> ¿En qué fecha fue publicado el libro de Harry Potter y la Piedra Filosofal?<br/>

    <input type="hidden" value="@Escape.EstadoJuego" name="sala">
    
    <input type="date" name="clave" placeholder="Ingrese su elección" autocomplete="off" size="30">
  </p>
  <button type="submit" class="btn btn-success">VALIDAR</button>
  <button onclick="alert('El mes y el día están escondidos en la imagen')" class="btn btn-warning"> Pista 1 </button>
  <button onclick="alert('Conta la posición de las letras rojas en su respectivo renglón para descubrir el año')" class="btn btn-warning"> Pista 2 </button>
  
</form>


</div>

Views/Escape/Habitacion2.cshtml
<div class="text-center">
  <h1>Sala 2</h1>
<P > 
    Bien hecho! Logramos ayudar a Harry, pero eso no es todo.
    Harry salió a la cocina pero la puerta tiene una contraseña que debemos descubrir.
    La contraseña es algo relacionado con la familia de su mejor amigo, Ron:
</P > 
<img src="\imagenes\sala 2.jpg">

<p>@ViewBag.Error</p>
<form method="post" action='@Url.Action("Habitacion","Escape")'>
  <p> ¿Cuantos hermanos tiene Ron Weasley?<br />

    <input type="hidden" value="@Escape.EstadoJuego" name="sala">

    <input type="number" name="clave" autocomplete="off" placeholder="Ingrese su elección" size="30">
  </p>
  <button type="submit" class="btn btn-success">VALIDAR</button>
  <button onclick="alert('Hay que descontar de la foto familiar a Ron, su mamá y su papá')" class="btn btn-warning"> Pista 1 </button>
  <button onclick="alert('1986 / 1655 * 5')" class="btn btn-warning"> Pista 2 </button>
</form>

Views/Escape/Habitacion3.cshtml
<div class="text-center">
  <h1>Sala 3</h1>
<p> 
    Harry logró salir de la cocina y llegó al salón pero debe descubrir la clave que abrirá la puerta.
    Para ello tiene que escribir el nombre de la casa de Hogwarts de color rojo que se ve en el poster.
</p>

<img src="\imagenes\sala 3.jpg">

<p>@ViewBag.Error</p>

<form method="post" action='@Url.Action("Habitacion","Escape")'>

  <input type="hidden" value="@Escape.EstadoJuego" name="sala">

  <p> ¿Cual es la casa de Hogwarts del poster en el sector rojo?<br />

  <input type="hidden" value="@Escape.EstadoJuego" name="sala">

  <input type="text" name="clave" autocomplete="off" placeholder="Ingrese su elección" size="30">

  </p>

  <button type="submit" class="btn btn-success">VALIDAR</button>
  

<button onclick="alert( 'Recuerda! Las casas de Hogwarts son: Slytherin,Hufflepuff,Ravenclaw y Gryffindor ')" class="btn btn-warning"> Pista 1 </button>
<button onclick="alert( ' Los pertenecientes a esta casa se destacan por su valentía ')" class="btn btn-warning"> Pista 2 </button>
</form>

Views/Escape/Habitacion4.cshtml
<div class="text-center">
  <h1>Sala 4</h1>
<p> 
    Genial, Harry logró salir de su casa y fuera se encontraba Hagrid el cual lo lleva hasta la entrada de la 
    estación 9 3/4. Al entrar Hagrid lo deja por su cuenta, no sin antes avisarle que para finalmente ingresar
    en esta estación magica, debe resolver un acertijo. 
</p>

<img src="\imagenes\sala 4.jpg">

<p>@ViewBag.Error</p>

<form method="post" action='@Url.Action("Habitacion","Escape")'>

  <input type="hidden" value="@Escape.EstadoJuego" name="sala">

  <p>¿Qué animal anda en cuatro patas por la mañana, en dos patas al mediodía y en tres durante la noche?<br />
  <input type="hidden" value="@Escape.EstadoJuego" name="sala">

  <input type="text" name="clave" autocomplete="off" placeholder="Ingrese su elección en minusculas" size="30">
  </p>

  <button type="submit" class="btn btn-success">VALIDAR</button>
  <button onclick="alert( 'Pensalo metaforicamente, no es un animal')" class="btn btn-warning"> Pista 1 </button>
   <button onclick="alert( 'Posee capacidad de razonamiento y conciencia ')" class="btn btn-warning"> Pista 2 </button>


</form>

Views/Escape/Index.cshtml
<div class="text-center">

<P>  Bienvenidos a mi vida, por si no me conocen me llamo <i> Harry 
    Potter </i>, tengo 11 años y hace unos días me llegó una carta para
     ir a la prestigiosa academia de Hogwarts, un colegio especial para 
     hechiceros y hechiceras. Esta carta dice que 
     tengo que ir a una estación especial pero hay un pequeño problema,
      mis tios me tiene encerrado en su casa. Necesito ayuda para llegar a la estación 9 3/4 
      ¿Quieren ayudarme? </P>

<img src="\imagenes\estacion.gif ">
<a href='@Url.Action("Comenzar","Escape")'><button type="button" class="btn btn-success">COMENZAR</button></a>


</div>

Views/Escape/Victoria.cshtml
<div class="text-center">
<h1>¡Victoria!</h1>
<h1>Harry logró atravesar la estación magica gracias a tu ayuda, enhorabuena!</h1>
<img src="\imagenes\festejo.gif "width="45%" height="auto">
<img src="\imagenes\victoria.gif " width="45%" height="auto"> 

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <img src="/imagenes/gg.png" >
    <h2 class="display-4">¿Listo para comenzar tu aventura hacia 9 3/4?</h2>
</div>
<!-- CARROUSEL --> 
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2" class="active"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="\imagenes\Carrousel 1.jpg" class="d-block w-100">
    </div>
    <div class="carousel-item">
      <img src="\imagenes\Carrousel 2.jpg" class="d-block w-100" height="30%">
    </div>
    <div class="carousel-item">
      <img src="\imagenes\Carrousel 3.jpg" class="d-block w-100" height="30%">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

Views/Home/Tutorial.cshtml
<h1>@ViewData["Title"]</h1>
<div class="text-center">

<h1>Tutorial</h1>
<p> <b> Durante este juego, se les irán presentando acertijos que deberas resolver para avanzar de sala en sala y ayudar a Harry a llegar a la estación 9 3/4 para cumplir su sueño de ser un mago en Hogwarts.</b> </p>

<img id="fotoPrincipalNoticia" title="Harry Potter y la piedra filosofal" src="\imagenes\tutorial 2.jpg" alt="Harry Potter y la piedra filosofal" >
<img id="fotoPrincipalNoticia" title="Harry Potter y la piedra filosofal" src="\imagenes\tutorial 3.jpg" alt="Harry Potter y la piedra filosofal" >
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SalaEscape</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Llegando a 9 3/4</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Tutorial">Tutorial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Escape" asp-action="Index">Jugar</a>
                        </li>
                    </ul>
                

            </div>

            </div>
        </nav>
    </header>
    <div class="container body-content">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Federico Gomboc - Shirly Jusid - Maia Raiter - 2022</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>